# ---- build stage ----
FROM node:18-alpine AS build
WORKDIR /app

# (optional) allow overriding paddles URL at build time
ARG REACT_APP_PADDLES_SERVER
ENV REACT_APP_PADDLES_SERVER=$REACT_APP_PADDLES_SERVER

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# ---- runtime stage ----
FROM nginxinc/nginx-unprivileged:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY openshift/nginx/default.conf /etc/nginx/conf.d/default.conf
